[package]
name = "wtfareu"
version = "1.0.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["debug"] }
serde_json = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true 
